### ISSUE TITLE
two keys in .env.example but three keys in README 

### ISSUE THREAD

**Issue by kerolloz** [icpc-scu-community/board-link-generator#3]
https://github.com/icpc-scu-community/board-link-generator/blob/5e333ad86ed05746dac50c21c341ec929c1a80e6/README.md#L16

https://github.com/icpc-scu-community/board-link-generator/blob/5e333ad86ed05746dac50c21c341ec929c1a80e6/.env.example#L1-L2

**Comment by 7oSkaaa** [comment]
we fixed it
